### ISSUE TITLE
Create an alternative simple template without multiproject stuff

### ISSUE THREAD

**Issue by boformer** [spbp/api-plugin-boilerplate#9]
This template is kind of advanced. This project should be renamed to "sponge-boilerplate-advanced" or "-pro", the other project should be just "sponge-boilerplate".

Additionally, we could also create a github organization named "spbp" (similar to https://github.com/h5bp/).

What do you think, @TBotV63?

**Comment by TBotV63** [comment]
That makes sense. But I'd name it something like sponge-boilerplate-multiproject. It's long, but describes it better.

But creating an organization for that purpose is really a good idea.

**Comment by boformer** [comment]
@TBotV63 https://github.com/h5bp/html5-boilerplate  
You are invited. 

I renamed this repo to `multiproject-boilerplate`.
I also created a repo for the simple boilerplate.

**Comment by TBotV63** [comment]
Thanks; I'm in :P
